### ISSUE TITLE
Tests run: Can not load "webpack" 

### ISSUE THREAD

**Issue by artdaw** [newtriks/generator-react-webpack#139]
I just generated a new project and tried to run tests:

WARN [preprocess]: Can not load "webpack"!
  TypeError: undefined is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/gleb/work/TTT/node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (/Users/gleb/work/TTT/node_modules/karma-webpack/index.js:72:9)
    at Tapable.applyPlugins (/Users/gleb/work/TTT/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:61:18)
    at Tapable.emitRecords (/Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:281:37)
    at Watching.<anonymous> (/Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:274:11
    at Tapable.applyPluginsAsync (/Users/gleb/work/TTT/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/gleb/work/TTT/node_modules/webpack/lib/Compiler.js:271:8)

**Comment by weblogixx** [comment]
Which version of the generator are you using? I dont get any errors with a fresh install.

**Comment by bishtawi** [comment]
I am getting the same error. I think one (or more) of the dev dependency libraries is getting updated (minor rev update I guess) and its breaking the build process.

**Comment by stylesuxx** [comment]
Had the same error, in my case it was karma-webpack at version 1.7.0, downgraded to 1.6.0 and tests run.

**Comment by CNBorn** [comment]
thanks @stylesuxx https://github.com/webpack/karma-webpack/commit/29fb1d801158f29cb0eb784edff69356705a7b74#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17 karma-webpack 1.7.0 requires karma >=0.13.2 but karma installed by this generator is 0.12.21

**Comment by weblogixx** [comment]
Could you try it again with 1.2.13? Just tried it, after the inclusion of https://github.com/newtriks/generator-react-webpack/pull/145 I dont see such errors anymore.

**Comment by weblogixx** [comment]
No feedback since a month. Closing this for now. Please feel free to reopen this issue if the problem still occurs. Otherwise, you could try to use the new version of the generator, which comes with karma-webpack 1.7.x and karma 0.13.9
