### ISSUE TITLE
  0:0  error  Cannot find module '../scope'

### ISSUE THREAD

**Issue by busla** [newtriks/generator-react-webpack#142]
Node: v0.12.7

I get this error on `grunt serve`:

```
grunt serve
Running "serve" task

Running "open:dev" (open) task

Running "webpack-dev-server:start" (webpack-dev-server) task
webpack-dev-server on port 8000  
Version: webpack 1.10.5     
      Asset     Size  Chunks             Chunk Names
    main.js  24.6 kB       0  [emitted]  main
main.js.map  26.9 kB       0  [emitted]  main

ERROR in ./src/components/main.js

/Users/nonni/Code/react-grunt/src/components/main.js
  0:0  error  Cannot find module '../scope'

✖ 1 problem (1 error, 0 warnings)


ERROR in ./src/components/main.js
Module build failed: SyntaxError: /Users/nonni/package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/nonni/Code/react-grunt/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/nonni/Code/react-grunt/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/nonni/Code/react-grunt/node_modules/babel-loader/index.js:69:12)
 @ multi main
webpack: bundle is now VALID.
```

**Comment by weblogixx** [comment]
Could it be possible that there is a path error in your module? Seems like it is unable to find the module scope.js. Could you please post some example code?

**Comment by busla** [comment]
I got pretty sceptical when most of my Yeoman generators were returning some weird package errors.

It ended up being an empty package.json in ~/ folder that was messing everything up :-)

Just cloned your repo right now to be sure and it works fine.

Thanks for the response.
