### ISSUE TITLE
Could not create app

### ISSUE THREAD

**Issue by thanzen** [newtriks/generator-react-webpack#148]
When I ran the command, I got the error below:
>yo react-webpack
C:\Users\user\AppData\Roaming\npm\node_modules\generator-react-webpack\generators\app\index.js:2
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as react-webpack:app] (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\user\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:243:16)

**Comment by weblogixx** [comment]
Hi @thanzen:
you seem to run an older version of node.js. The generator is compatible with node version 4 and upwards.

**Comment by thanzen** [comment]
That is. After upgraded node to latest version, everything just works fine.
Thanks @weblogixx
