### ISSUE TITLE
error when i try to install

### ISSUE THREAD

**Issue by original001** [newtriks/generator-react-webpack#151]
$ yo react-webpack
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as react-webpack:app] (store.js:40:23)
    at Store.get (store.js:64:35)
    at Environment.get (environment.js:243:16)

OS Windows 7
$ npm ls -g --depth=0
C:\Users\vtolstikov\AppData\Roaming\npm              
├── babel@5.8.23                                     
├── bem@0.10.1                                       
├── bower@1.5.3                                      
├── generator-react-webpack@2.2.1                    
├── generator-react-webpack-alt@1.3.0                
├── grunt-cli@0.1.13                                 
├── less@2.5.2                                       
├── webpack@1.12.2                                   
└── yo@1.4.8

**Comment by weblogixx** [comment]
@original001: The generator is built using es2015, you will need at least node version 4.0.0 to use it. This should also be visible as a warning when trying to install the package.

**Comment by original001** [comment]
update nodejs, and It's work! Thanks
