### ISSUE TITLE
Running yo react-webpack SyntaxError

### ISSUE THREAD

**Issue by pavelbinar** [newtriks/generator-react-webpack#155]
Error
```
(! 560)->  yo react-webpack
/Users/pavelbinar/.nvm/v0.12.0/lib/node_modules/generator-react-webpack/generators/app/index.js:2
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as react-webpack:app] (/Users/pavelbinar/.nvm/v0.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/Users/pavelbinar/.nvm/v0.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/Users/pavelbinar/.nvm/v0.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:243:16)
```

System Information

```
(! 561)->  node --version && npm --version
v0.12.0
3.3.8
```
OS X EL Capitan (10.11)

**Comment by weblogixx** [comment]
@pavelbinar: This is a known issue. The generator needs at least node Version 4.0. It should also display this when you try to install it. 

Please update your version of node to a current one (4.0.0 or higher) to use the generator.
