### ISSUE TITLE
'os-homedir' missing after fresh install

### ISSUE THREAD

**Issue by mrzmyr** [newtriks/generator-react-webpack#172]
```bash
❯ yo react-webpack:component my/component
module.js:340
    throw err;
    ^

Error: Cannot find module 'os-homedir'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/configstore/node_modules/osenv/osenv.js:5:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

Or should this be filed in [osenv](https://github.com/npm/osenv) ?

cc @isaacs

**Comment by weblogixx** [comment]
Hi @mrzmyr,

I dont get any errors like this when creating new components. I once had a similiar problem where some dependencies where not correctly installed (in my case it was lodash after updating). Could you run npm install in your project directory and look if it installs any missing dependencies? If this does not help, what happens if you manually install os-homedir?

**Comment by weblogixx** [comment]
Nothing new in nearly a month. Closing this for now.
@mrzmyr: Please feel free to open new issues if you have still problems with the generator.
