### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by cheshire137** [newtriks/generator-react-webpack#184]
```
% yo react-webpack
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes

/usr/local/lib/node_modules/generator-react-webpack/generators/app/index.js:2
let generator = require('yeoman-generator');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._storeAsPath.Object.defineProperty.get [as react-webpack:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:244:16)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:277:24)
```

**Comment by cheshire137** [comment]
Never mind, I installed Node v4 from https://nodejs.org/en/blog/release/v4.0.0/ and it works now.
