### ISSUE TITLE
lint task errors because of missing estraverse-fb module

### ISSUE THREAD

**Issue by louisremi** [newtriks/generator-react-webpack#196]
Hi, I just updated my `generator-react-webpack-redux` today, created a new project and tried to run the lint task, after a few modifications. Here's the error that was logged:
```
louisremi@zenbook:~/Workspace/matchonlyme$ npm run lint

> wannamatchme@0.0.1 lint /home/louisremi/Workspace/wannamatchme
> eslint ./src

Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at monkeypatch (/home/louisremi/Workspace/wannamatchme/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/home/louisremi/Workspace/wannamatchme/node_modules/babel-eslint/index.js:385:5)
    at parse (/home/louisremi/Workspace/wannamatchme/node_modules/eslint/lib/eslint.js:578:27)
    at EventEmitter.module.exports.api.verify (/home/louisremi/Workspace/wannamatchme/node_modules/eslint/lib/eslint.js:716:19)
    at processText (/home/louisremi/Workspace/wannamatchme/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/home/louisremi/Workspace/wannamatchme/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/home/louisremi/Workspace/wannamatchme/node_modules/eslint/lib/cli-engine.js:603:23)
```

**Comment by louisremi** [comment]
It's a bug with eslint 2.3.0 that should soon be fixed, apparently: https://github.com/eslint/eslint/issues/5476

**Comment by justo** [comment]
`npm start` crashes because of this bug, even on a brand new project.

**Comment by weblogixx** [comment]
I just released an updated package that fixes the eslint range. Should work now correctly for new projects.
