### ISSUE TITLE
Failed at the reactWebpack@0.0.1 start script 'node server.js --env=dev'

### ISSUE THREAD

**Issue by brentjm** [newtriks/generator-react-webpack#201]
Can't start the development server error message below.

[npm-debug.log.zip](https://github.com/newtriks/generator-react-webpack/files/173951/npm-debug.log.zip)

$npm start

> reactWebpack@0.0.1 start /home/userfiles/brent/Documents/react-webpack
> node server.js --env=dev

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at net.js:1372:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/home/brent/.nvm/versions/node/v5.6.0/bin/node" "/home/brent/.nvm/versions/node/v5.6.0/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! reactWebpack@0.0.1 start: `node server.js --env=dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactWebpack@0.0.1 start script 'node server.js --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactWebpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --env=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactWebpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactWebpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/userfiles/brent/Documents/react-webpack/npm-debug.log

**Comment by brentjm** [comment]
My mistake. It appears I had a python server running on port 8000, which cause the npm server to fail. Working fine now.
