### ISSUE TITLE
Error in starting 

### ISSUE THREAD

**Issue by rukshn** [newtriks/generator-react-webpack#222]
When running the npm run command after freshly installing react webpack generator I'm getting the following error. Any idea how to fix it?

```
> node server.js --env=dev

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1230:14)
    at listen (net.js:1266:10)
    at net.js:1375:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 4.1.21-1-MANJARO
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! movie@0.0.1 serve: `node server.js --env=dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the movie@0.0.1 serve script 'node server.js --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the movie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --env=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs movie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls movie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/
```

**Comment by Hosar** [comment]
Same here, I'm getting a similar error:

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! testOfReactWebPackGen@0.0.1 serve: `node server.js --env=dev`
npm ERR! Exit status 1

**Comment by weblogixx** [comment]
Hi @Hosar,

you already have some other service listening on port 8000. See this line:

```
Error: listen EADDRINUSE 127.0.0.1:8000
```

Please make sure nothing else runs on port 8000 before you run npm start.
