### ISSUE TITLE
why  yo react-webpack-redux:reducer my/namespaced/reducers/name error

### ISSUE THREAD

**Issue by yunji7** [newtriks/generator-react-webpack#321]
yo react-webpack-redux:reducer my/namespaced/reducers/name
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Line 48: Duplicate data property in object literal not allowed in strict mode
    at throwError (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:2824:21)
    at throwErrorTolerant (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:2836:24)
    at parseObjectInitialiser (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3410:29)
    at parsePrimaryExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3571:20)
    at parseLeftHandSideExpressionAllowCall (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprim
a.js:3683:61)
    at parsePostfixExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3723:20)
    at parseUnaryExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3790:16)
    at parseBinaryExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3880:16)
    at parseConditionalExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:3940:
16)
    at parseAssignmentExpression (C:\Users\may\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\.15001.1001.0-dev-harmony-fb@esprima-fb\esprima.js:4193:1
6)

**Comment by sthzg** [comment]
hi @yunji7, sorry for the late reply. I've been busy the last weeks and couldn't monitor these issues close enough. Did you try asking your question on the [generator-react-webpack-redux](https://github.com/stylesuxx/generator-react-webpack-redux) project?
